services:
  network-deploy-service:
    networks:
      - eazybank

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

#services: #Per ottimizzare il docker compose inseriamo le parti ripetitive in questo file e verranno richiamate nel docker compose
#  network-deploy-service:
#    networks:
#      - eazybank
#
#  microservice-base-config:
#    extends:
#      service: network-deploy-service
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbit"
#
#  microservice-configserver-config:
#    extends:
#      service: microservice-base-config
#    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
#      SPRING_PROFILES_ACTIVE: "default"
